apiVersion: v1
kind: Secret
metadata:
  name: todoapp-mongodb
  namespace: mern-app
type: Opaque
data:
  MONGODB_ROOT_USER: cm9vdA==
  MONGODB_ROOT_PASSWORD: ZXZhbnJvb3RwYXNzd29yZA==
  MONGODB_USER: ZXZhbg==
  MONGODB_PASSWORD: ZXZhbnRvZG9hcHA=
  MONGODB_DATABASE: dG9kb2FwcA==

# export MONGODB_PASSWORD=$(kb -- get secret --namespace mern-app todoapp-mongodb -o jsonpath="{.data.mongodb-passwords}" | base64 -d | awk -F',' '{print $1}')
# export MONGODB_ROOT_PASSWORD=$(kb -- get secret --namespace mern-app todoapp-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 -d)  
# kb -- port-forward --namespace mern-app svc/todoapp-mongodb 27017:27017 &
# mongosh --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD --eval 'db.getSiblingDB("todoapp").createUser({user: "evan", pwd: $MONGODB_PASSWORD, roles: [{ role: "readWrite", db: "todoapp" }, { role: "dbAdmin", db: "todoapp" }]})'

# kubectl port-forward --namespace mern-app svc/todoapp-mongodb 27017:27017 &
# mongosh --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD

export ODOO_PASSWORD=$(kb -- get secret --namespace "wordpress" odoo -o jsonpath="{.data.odoo-password}" | base64 -d)
  # echo -n "root" | base64
  # echo -n "evanrootpassword" | base64
  # echo -n "evan" | base64
  # echo -n "evantodoapp" | base64
  # echo -n "todoapp" | base64