apiVersion: v1
kind: Service
metadata:
  name: mern-app
  namespace: mern-app # namespace on which we deploy the resources
spec:
  selector:
    app: mern-app
  ports:
    - name: http
      protocol: TCP
      port: 80 # port of the service
      targetPort: 5000 # port that app exposes from the pod

# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose convert -f docker-compose-dev.yml -o mern-k8s/
#     kompose.version: 1.30.0 (9d8dcb518)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: mern-app
#   name: mern-app
#   namespace: default
# spec:
#   ports:
#     - name: "5000"
#       port: 5000
#       targetPort: 5000
#   selector:
#     io.kompose.service: mern-app
# status:
#   loadBalancer: {}